### ISSUE TITLE
Tristan says he’s done 22 hours this week but thats actually over more than a week

### ISSUE THREAD

**Issue by raretec** [tjmisko/ChallengeLog#1]

**Comment by tjmisko** [comment]
looks fine to me, please provide steps to reproduce

**Comment by raretec** [comment]
git checkout 2f667eb4f2aea2370353c836c2c0d9b0fc387a8a

**Comment by tjmisko** [comment]
@raretec First date in the file is 2024-05-19 (Sunday) and the last date is 2024-05-24 (Friday).

My week begins on Sunday at 00:00 and ends on Saturday at 23:59, which would place both of those dates in the same week, i.e. 2024w21.
